### ISSUE TITLE
[Task]: Replace existing keys with a single consistent key list.

### ISSUE THREAD

**Issue by Tearran** [armbian/configng#259]
### Task description

- [x] List module_options key
- [x] List menu object JSON keys
- [ ] Replace existing keys with a single consistent key list.
- [ ] Add a way to migrate to the new keys
- [ ] Refactor generate_module_option to output "menu object" json 
- [ ] Remove "./tools/json/config.software.json"
- [ ] Add to assemble 

```
id
description
status
sub
about
command
author
condition
```

```
author
feature 
example
desc
status
```
Example updates
module_options array:
```
development_module_options+=(
    ["module_template,author"]="@armbian"
    ["module_template,maintainer"]="@Tearran"
    ["module_template,id"]="module_template"
    ["module_template,parent_id"]="Development"
    ["module_template,about"]="If system is changed. How?"
    ["module_template,description"]="Example template module for advanced and unattended interface."
    ["module_template,commands"]="help foo bar status"
    ["module_template,status"]="review"
)
```
